version: "3"

services:  
  nginx:
    image: rodrigotrentinrossi/nginx-gateway
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - system_network  

  question_service:
    image: rodrigotrentinrossi/question-service:latest
    container_name: question_service
    env_file:
      - ./envs/question-service.env
    networks:
      - system_network
    expose:
      - "4001"

  respondent_service:
    image: rodrigotrentinrossi/respondent-service:latest
    container_name: respondent_service
    env_file:
      - ./envs/respondent-service.env
    networks:
      - system_network
    expose:
      - "4002"

volumes:  
  mongodb-db:

networks:
  system_network:
    external:
      name: system_network
